### ISSUE TITLE
DebugSerialを直接このリポジトリに入れるのをやめたい

### ISSUE THREAD

**Issue by Kotakku** [robocon-ichinoseki-Ateam/StandardControlLibrary#5]
DebugSerialはこのライブラリに限ったものでは無いので独立させたいからこのリポジトリの中にあるDebugSerialは常に[ここ](https://github.com/robocon-ichinoseki-Ateam/DebugSerial)にあるものを持ってくるようにしたい。submoduleを使えば行けるらしい?

**Comment by surpace0924** [comment]
すみません
戻しておきます
